"""empty message

Revision ID: 2426cef48736
Revises: d285c7a3f70c
Create Date: 2016-11-02 21:42:00.011051

"""

# revision identifiers, used by Alembic.
revision = '2426cef48736'
down_revision = 'd285c7a3f70c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_name', table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index('ix_category_name', 'category', ['name'], unique=False)
    ### end Alembic commands ###
