"""empty message

Revision ID: 5529736d2988
Revises: 2426cef48736
Create Date: 2016-11-02 22:26:13.106228

"""

# revision identifiers, used by Alembic.
revision = '5529736d2988'
down_revision = '2426cef48736'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('accept_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'accept_time')
    ### end Alembic commands ###
