"""empty message

Revision ID: d285c7a3f70c
Revises: None
Create Date: 2016-11-02 21:33:47.613263

"""

# revision identifiers, used by Alembic.
revision = 'd285c7a3f70c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_active'), 'category', ['active'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('employer_email', sa.String(), nullable=True),
    sa.Column('employee', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('compensation', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_active'), table_name='category')
    op.drop_table('category')
    ### end Alembic commands ###
